"""add canonical/indexability/hreflang/schema columns to pages

Revision ID: b090e7be556f
Revises: 78b051455aef
Create Date: 2026-07-17 17:49:45.615161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b090e7be556f'
down_revision: Union[str, Sequence[str], None] = '78b051455aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('canonical_url', sa.String(length=2048), nullable=True))
    op.add_column('pages', sa.Column('is_indexable', sa.Boolean(), nullable=True))
    op.add_column('pages', sa.Column('hreflang_json', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('schema_types_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'schema_types_json')
    op.drop_column('pages', 'hreflang_json')
    op.drop_column('pages', 'is_indexable')
    op.drop_column('pages', 'canonical_url')
    # ### end Alembic commands ###
