"""add next_run_at to crawl_configs

Revision ID: be15625ea016
Revises: b090e7be556f
Create Date: 2026-07-20 10:34:16.273761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be15625ea016'
down_revision: Union[str, Sequence[str], None] = 'b090e7be556f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_configs', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_configs', 'next_run_at')
    # ### end Alembic commands ###
